spring:
  thymeleaf:
    cache: false #\u8FD9\u91CC\u9875\u9762\u7F13\u5B58\u9ED8\u8BA4\u4E3Atrue\uFF0C\u5F00\u53D1\u8FC7\u7A0B\u4E2D\u53EF\u8BBE\u7F6E\u4E3Afalse
  messages:
    basename: i18n.login
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC
    username: root
    password: passwd
  redis:
    host: 127.0.0.1
    port: 6379

